# Generated by Django 4.2.30 on 2026-08-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(db_index=True, max_length=10)),
                ('rack_id', models.IntegerField(default=0)),
                ('retail_price', models.FloatField(db_index=True)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
            ],
            options={
                'ordering': ['retail_price'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='fuel_optimi_latitud_cbced2_idx')],
            },
        ),
    ]
